#include "std_lib_facilities.h"
int main() 
{
    cout<<" Chapter 2: Definition of Terms\n\n";
    
    cout<<"//: Begins a comment. Everything after // on the same line is ignored by the compiler. \n\n";
    cout<<"executable: The program file (e.g., .exe on Windows) produced by the compiler that you can run. \n\n";
    cout<<"main(): The main function where every C++ program starts executing.\n\n";
    cout<<"<<: The output operator, used with count to send data to the standard output.\n\n";
    cout<<"function: A named sequence of instructions that performs a specific task.\n\n";
    cout<<"object code: The machine code generated by the compiler from source code, before linking.\n\n";
    cout<<"C++: A general-purpose programming language that supports both procedural and object-oriented programming.\n\n";
    cout<<"header: A file that contains declarations for functions, classes, etc., to be shared between programs.\n\n";
    cout<<"output: The information a program produces (usually shown on screen, saved to a file, etc.)\n\n";
    cout<<"IDE: Integrated Development Environment, a tool that combines the editor, compiler, debugger, etc.\n\n";
    cout<<"program: A set of instructions (source code) written in a programming language.\n\n";
    cout<<"compiler: A program that translates source code (like .cpp files) into machine code (object code or executable).\n\n";
    cout<<"#include: A directive that tells the computer to include contents from another file (like a header). \n\n";
    cout<<"source code: The original human-readable code you write in a programming language.\n\n";
    cout<<"compile-time error: An error found by a compiler when translating the program.\n\n";
    cout<<"library: A collection of pre-written code (functions, classes, etc.) you can reuse in your program.\n\n";
    cout<<"statement: A complete instruction in C++ (e.g. declaration, assignment, or a function call).\n\n";
    cout<<"cout: The standard output stream in C++ (character output/see out).\n\n";
    cout<<"linker: A program that combines object code files and libraries into a single executable file.\n\n";

    cout<<" Chapter 3: Definitions of Terms\n\n";

    cout<<"object: A region of memory with a type that specifies what kind of information can be placed in it. A named object is called a variable.\n\n";
    cout<<"definition: A statement that introduces a new name into a program and sets aside memory for a variable is called definition. A statement can and often should provide an initial value.\n\n";
    cout<<"cin: This refers to the standard input stream defined in the standard library. 'see-in' or 'character input'\n\n";
    cout<<">>: The input operator, used to specify where the input goes.\n\n";
    cout<<"values: Data items which we put into variables.\n\n";
    cout<<"Variable Types:\n\n";
    cout<<"int: Integer, int number_of_steps = 39.\n\n";
    cout<<"double: floating_point numbers; double flying_time = 3.5.\n\n";
    cout<<"char: Individual character string; char decimal_point = '.'.\n\n";
    cout<<"bool: Logical variables; bool tap_on = true.\n\n";
    
    cout<<"floating point: A floating point is the computers approximation to the mathematical concept of a real number.\n\n";
    cout<<"operations: Operations are determined by variable types.\n\n";
    cout<<"=(assignment): Available for: bool, char, int, double, and string.\n\n";
    cout<<"+(addition): Available for: int, and double.\n\n";
    cout<<"+(concatenation): Available for: strings.\n\n";
    cout<<"-(subtraction): Available for: int, and double.\n\n";
    cout<<"*(multiplication): Avaialble for: int and double.\n\n";
    cout<<"/(division): Available for: int and double. \n\n";
    cout<<"%(remainder(modulo)): Available for: int. \n\n";
    cout<<"++(increment by 1): Available for int, and double. \n\n";
    cout<<"--(decrement by 1): Available for int, and double. \n\n";
    cout<<"+=n(increment by n): Available for int, and double. \n\n";
    cout<<"+=(add to end): Available for \n\n";

    cout<<"\n\n";
    

    keep_window_open();
    return(0);
}